### ISSUE TITLE
Old strings are not cleared when running the tool

### ISSUE THREAD

**Issue by msavaria** [apcurium/resxible#1]
When running the tool, localized strings are appended to the file, but old strings are never cleared. Resources files should be cleared and regenerated every time the tool is run.

**Comment by matthieugd** [comment]
We should provide an option for that. Thank you.

**Comment by msavaria** [comment]
Hello, I'm following up on this issue. Any plan to get this fixed soon? :)

**Comment by matthieugd** [comment]
We are accepting Pull Request :)

**Comment by Costo** [comment]
This should be optional. You might have some resource strings that are on only one platform and Resxible should not remove them automatically.
